// The visible 3-lane track surface, built ONCE here and used by BOTH the game renderer and the
// align editor, so what you position in the editor is exactly what races. It's an opaque ribbon
// (dark asphalt + optional side shoulders) with bright lane dividers + edge lines, laid along the
// curved path. Opaque + raised slightly so the map's own road texture never shows through and the
// 3-lane read is unmistakable.
import * as THREE from 'three';
import { TRACK_W, RACE_LEN, TRACK_LEN, LAP_TARGET, LANES } from '../shared/constants';
import { CurvedTrack } from './track-path';
import type { TrackPath } from './map-world';

const SEGMENTS = 200;          // smoothness along the curve
const Y_ROAD = 0.6;            // lift the whole track above the map road so it never z-fights
const Y_PAINT = 0.05;          // paint sits just above the road surface

export interface SurfaceOpts { laneScale: number; shoulder: number; }

export function surfaceOptsFromPath(path?: TrackPath): SurfaceOpts {
  return { laneScale: path?.laneScale ?? 1, shoulder: path?.shoulder ?? 0 };
}

/**
 * Build the full track surface group for a curve. Half-width of the *lanes* = TRACK_W/2 * laneScale;
 * the road mesh extends an extra `shoulder` on each side. All geometry is generated by walking the
 * curve and offsetting perpendicular to its tangent, so it bends with the path.
 */
export function buildTrackSurface(curve: CurvedTrack, opts: SurfaceOpts): THREE.Group {
  const group = new THREE.Group();
  const laneHalf = (TRACK_W / 2) * opts.laneScale;
  const roadHalf = laneHalf + opts.shoulder;

  const center: THREE.Vector3[] = [];
  const perp: THREE.Vector3[] = [];
  for (let i = 0; i <= SEGMENTS; i++) {
    const z = (i / SEGMENTS) * RACE_LEN;
    const c = curve.sample(z, 0).pos;
    const tan = curve.sample(Math.min(z + 1, RACE_LEN), 0).pos.sub(c).setY(0);
    if (tan.lengthSq() < 1e-9) tan.set(0, 0, 1);
    tan.normalize();
    center.push(c);
    perp.push(new THREE.Vector3(tan.z, 0, -tan.x));   // right-hand perpendicular on the ground
  }

  // --- Opaque road ribbon (asphalt + shoulders), full roadHalf width. Slightly emissive so it
  // never reads as black against dark terrain. ---
  group.add(ribbon(center, perp, roadHalf, Y_ROAD,
    new THREE.MeshStandardMaterial({ color: 0x3b4250, emissive: 0x1a1e26, roughness: 0.9, metalness: 0 })));

  // --- Shoulder apron: a lighter band on the outer shoulders so the 3 drivable lanes read as
  // clearly distinct from the covering apron. Only drawn if there's a shoulder. ---
  if (opts.shoulder > 0.5) {
    group.add(edgeBand(center, perp, laneHalf, roadHalf, Y_ROAD + 0.02,
      new THREE.MeshStandardMaterial({ color: 0x4b5366, emissive: 0x20242e, roughness: 1 })));
  }

  // --- Lane fills: BRIGHT, high-contrast alternating shades (emissive) so each of the 3 lanes
  // pops against any map terrain. ---
  const laneW = (laneHalf * 2) / LANES;
  for (let lane = 0; lane < LANES; lane++) {
    const inner = -laneHalf + lane * laneW;
    const outer = inner + laneW;
    const lit = lane % 2 === 0;
    const mat = new THREE.MeshStandardMaterial({
      color: lit ? 0x6b7488 : 0x2a3040, emissive: lit ? 0x2a3242 : 0x12161e, roughness: 0.85 });
    group.add(edgeBand(center, perp, inner, outer, Y_ROAD + 0.03, mat));
  }

  // --- Bold lane dividers + edge lines, drawn as THICK emissive ribbons (real width, so they read
  // at any distance — unlike 1px THREE.Line). Dividers are bright white; the two track edges are
  // glowing cyan so the 3-lane boundary is unmistakable. ---
  const DIV_W = Math.max(0.6, laneW * 0.05);    // divider half-handled inside band()
  const EDGE_W = Math.max(1.2, laneW * 0.09);
  const white = new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 0.5, roughness: 0.5 });
  const cyan = new THREE.MeshStandardMaterial({ color: 0x36d1dc, emissive: 0x36d1dc, emissiveIntensity: 0.9, roughness: 0.4 });
  const stripe = (off: number, w: number, mat: THREE.Material) =>
    group.add(edgeBand(center, perp, off - w / 2, off + w / 2, Y_PAINT + Y_ROAD, mat));
  for (let d = 1; d < LANES; d++) stripe(-laneHalf + d * laneW, DIV_W, white);   // dashed-look dividers
  stripe(-laneHalf, EDGE_W, cyan);
  stripe(laneHalf, EDGE_W, cyan);

  // --- Lap boundary lines across the lanes (thick white bands). ---
  for (let lap = 1; lap < LAP_TARGET; lap++) {
    const m = curve.sample(TRACK_LEN * lap, 0);
    const tan = curve.sample(Math.min(TRACK_LEN * lap + 1, RACE_LEN), 0).pos.sub(m.pos.clone()).setY(0).normalize();
    const pr = new THREE.Vector3(tan.z, 0, -tan.x);
    const ly = m.pos.y + Y_PAINT + Y_ROAD + 0.02;   // ride the point's hill height
    const corners = [
      m.pos.clone().addScaledVector(pr, laneHalf).setY(ly),
      m.pos.clone().addScaledVector(pr, -laneHalf).setY(ly),
    ];
    group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(corners),
      new THREE.LineBasicMaterial({ color: 0xffffff })));
  }

  return group;
}

/** A solid ribbon of given half-width along the centerline. */
function ribbon(center: THREE.Vector3[], perp: THREE.Vector3[], half: number, y: number,
                mat: THREE.Material): THREE.Mesh {
  const pos: number[] = [];
  for (let i = 0; i < center.length - 1; i++) {
    // Each vertex keeps its centerline Y (the track's per-point hill) PLUS the lift `y`, so the
    // road follows elevation changes instead of flattening to a constant height.
    const rA = center[i]!.clone().addScaledVector(perp[i]!, half); rA.y += y;
    const lA = center[i]!.clone().addScaledVector(perp[i]!, -half); lA.y += y;
    const rB = center[i + 1]!.clone().addScaledVector(perp[i + 1]!, half); rB.y += y;
    const lB = center[i + 1]!.clone().addScaledVector(perp[i + 1]!, -half); lB.y += y;
    pos.push(lA.x, lA.y, lA.z, rA.x, rA.y, rA.z, lB.x, lB.y, lB.z);
    pos.push(rA.x, rA.y, rA.z, rB.x, rB.y, rB.z, lB.x, lB.y, lB.z);
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  geo.computeVertexNormals();
  (mat as THREE.MeshStandardMaterial).side = THREE.DoubleSide;   // show from above AND below
  const m = new THREE.Mesh(geo, mat); m.receiveShadow = true; return m;
}

/** A band between two signed offsets (inner..outer) from the centerline. */
function edgeBand(center: THREE.Vector3[], perp: THREE.Vector3[], inner: number, outer: number,
                  y: number, mat: THREE.Material): THREE.Mesh {
  const pos: number[] = [];
  for (let i = 0; i < center.length - 1; i++) {
    const oA = center[i]!.clone().addScaledVector(perp[i]!, outer); oA.y += y;
    const iA = center[i]!.clone().addScaledVector(perp[i]!, inner); iA.y += y;
    const oB = center[i + 1]!.clone().addScaledVector(perp[i + 1]!, outer); oB.y += y;
    const iB = center[i + 1]!.clone().addScaledVector(perp[i + 1]!, inner); iB.y += y;
    pos.push(iA.x, iA.y, iA.z, oA.x, oA.y, oA.z, iB.x, iB.y, iB.z);
    pos.push(oA.x, oA.y, oA.z, oB.x, oB.y, oB.z, iB.x, iB.y, iB.z);
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  geo.computeVertexNormals();
  (mat as THREE.MeshStandardMaterial).side = THREE.DoubleSide;   // show from above AND below
  return new THREE.Mesh(geo, mat);
}

